name: "Java Maven"

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        description: "java version"
        type: string
        required: true
      DISTRIBUTION:
        description: "java distribution"
        required: true
      CACHE:
        description: "java distribution"
        required: true           
jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.JAVA_VERSION}}
        distribution: ${{ inputs.DISTRIBUTION}}
        cache: ${{ inputs.CACHE}}
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
