name: "Java Maven"

inputs:
  JAVA_VERSION:
    description: "Java version to use"
    required: true
  DISTRIBUTION:
    description: "Java distribution to use"
    required: true
  CACHE:
    description: "Cache strategy for Maven dependencies"
    required: true          

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.JAVA_VERSION }}
        distribution: ${{ inputs.DISTRIBUTION }}
        cache: ${{ inputs.CACHE }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      shell: bash