name: "Java Maven"

inputs:
  JAVA_VERSION:
    description: "java version"
    required: true
  DISTRIBUTION:
    description: "java distribution"
    required: true
  CACHE:
    description: "java cache"
    required: true          

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.JAVA_VERSION}}
        distribution: ${{ inputs.DISTRIBUTION}}
        cache: ${{ inputs.CACHE}}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
