name: "Java Maven"

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        description: "java version"
        type: string
        required: true
      DISTRIBUTION:
        description: "java distribution"
        type: string
        required: true
      CACHE:
        description: "java cache"
        type: string
        required: true           
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: eherediam/central-workflow/java@main
      with:
        JAVA_VERSION: ${{ inputs.JAVA_VERSION}}
        DISTRIBUTION: ${{ inputs.DISTRIBUTION}}
        CACHE: ${{ inputs.CACHE}}